version: '3'
services:
  mongo:
    image: mongo
    container_name: localmongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alura-challenge
      - MONGO_INITDB_ROOT_PASSWORD=alura-challenge
      - MONGO_INITDB_DATABASE=alura-challenge
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'